# Generated by Django 5.1.7 on 2025-03-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='qualifications',
        ),
    ]
