# Generated by Django 5.1.7 on 2025-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_remove_instructor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Verification Status'),
        ),
    ]
