# Generated by Django 5.1.7 on 2025-05-26 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('students', '0005_student_groups_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='students.student'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='students.student'),
        ),
    ]
