# Generated by Django 5.1.7 on 2025-04-01 13:49

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.ImageField(help_text='Maximum file size: 10MB. Allowed formats: JPG, JPEG, PNG', upload_to='course_thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), courses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(help_text='Maximum file size: 300MB. Allowed formats: MP4, WEBM', upload_to='course_demos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), courses.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
