# Generated by Django 5.1.7 on 2025-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('graphic_design', 'Graphic Design'), ('data_science', 'Data Science & Analytics'), ('digital_marketing', 'Digital Marketing'), ('personal_finance', 'Personal Finance'), ('entrepreneurship', 'Entrepreneurship & Startups'), ('photography', 'Photography & Videography'), ('fitness', 'Fitness & Wellness'), ('language', 'Language Learning'), ('mobile_dev', 'Mobile App Development'), ('music', 'Music & Audio Production'), ('ui_ux', 'UI/UX Design'), ('software_tools', 'Software & Tools'), ('teaching', 'Teaching & Academics'), ('project_management', 'Project Management & Leadership')], max_length=100),
        ),
    ]
