# Generated by Django 5.1.7 on 2025-05-24 18:03

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursevideo_alter_content_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseVideo',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='video',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Maximum file size: 300MB. Allowed formats: MP4, WEBM', null=True, upload_to='course_demos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), courses.models.validate_file_size]),
        ),
    ]
