# Generated by Django 5.1.7 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_coursevideo_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload_to=content_upload_to'),
        ),
    ]
