# Generated by Django 5.1.7 on 2025-05-26 05:35

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cloudfront_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.content_upload_to),
        ),
    ]
