# Generated by Django 5.1.7 on 2025-05-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_content_cloudfront_url_alter_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='cloudfront_url',
        ),
    ]
