# Generated by Django 5.1.7 on 2025-04-17 18:57

import django.db.models.deletion
import django.utils.timezone
import forums.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_content_content_type'),
        ('instructors', '0005_alter_instructor_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forums', to='instructors.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender_type', models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=forums.models.forum_file_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_type', models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forums.forum')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forums.forummessage')),
            ],
        ),
        migrations.CreateModel(
            name='ForumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='forums.forum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('forum', 'student')},
            },
        ),
    ]
